//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERGLauncher.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERGLauncher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Brand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddBrand {
            get {
                return ResourceManager.GetString("AddBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} already exists. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brand Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to launch {0} ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToLaunch {
            get {
                return ResourceManager.GetString("DoYouWantToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to remove {0} ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoYouWantToRemove {
            get {
                return ResourceManager.GetString("DoYouWantToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutableFile {
            get {
                return ResourceManager.GetString("ExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable file not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutableFileNotFound {
            get {
                return ResourceManager.GetString("ExecutableFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable files (*.exe)|*.exe に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExecutableFiles {
            get {
                return ResourceManager.GetString("ExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to start the executable file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FailedStartExecutableFile {
            get {
                return ResourceManager.GetString("FailedStartExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generals に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Generals {
            get {
                return ResourceManager.GetString("Generals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image files (*.jpg, *.jpeg, *.bmp, *.png)|*.jpg;*.jpeg;*.bmp;*.png に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageFiles {
            get {
                return ResourceManager.GetString("ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unexpected exception has occurred. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OnUnexpectedException {
            get {
                return ResourceManager.GetString("OnUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open executable file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenExecutableFile {
            get {
                return ResourceManager.GetString("OpenExecutableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open icon file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenIconFile {
            get {
                return ResourceManager.GetString("OpenIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectTheme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectTheme {
            get {
                return ResourceManager.GetString("SelectTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sync System Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SyncTheme {
            get {
                return ResourceManager.GetString("SyncTheme", resourceCulture);
            }
        }
    }
}
